# -*- coding: utf-8 -*-
"""banknoteAuth.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12KZDMqDpsdnIfip3LStrRTawENx-Zljr
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/home/hunter/Dataset/BankNote_Authentication.csv')

df

x= df.iloc[:,:-1]
y= df.iloc[:,-1]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state = 0)

from sklearn.ensemble import RandomForestClassifier
cf = RandomForestClassifier()
cf.fit(x_train,y_train)

y_pred = cf.predict(x_test)

from sklearn.metrics import accuracy_score
cnf = accuracy_score(y_test,y_pred)
cnf

import pickle
pickel_out = open("cf.pkl" , "wb")
pickle.dump(cf,pickel_out)
pickel_out.close()

